name = "easytech-contact-worker"
main = "cloudflare/contact-worker.js"
compatibility_date = "2026-03-20"
workers_dev = false
account_id="78617e32f258e9f198318d505c289753"

[[routes]]
pattern = "easytechvancouver.ca/api/contact"
zone_name = "easytechvancouver.ca"

[[routes]]
pattern = "www.easytechvancouver.ca/api/contact"
zone_name = "easytechvancouver.ca"

[vars]
SEND_FROM = "admin@easytechvancouver.ca"
# Gmail inbox that should receive contact form notifications.
SEND_TO = "abhijeet.karmaker@gmail.com"
AUTO_REPLY_ENABLED = "true"

[[send_email]]
name = "EMAIL"
destination_address = "abhijeet.karmaker@gmail.com"
